### ISSUE TITLE
Cannot add vertex: a vertex with name "outputs" already exists

### ISSUE THREAD

**Issue by ghost** [tahaemara/yolo-custom-object-detector#6]
Exception in thread "main" java.lang.IllegalStateException: Cannot add vertex: a vertex with name "outputs" already exists
	at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:641)
	at org.nd4j.base.Preconditions.checkState(Preconditions.java:304)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.addVertex(ComputationGraphConfiguration.java:924)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.addLayer(ComputationGraphConfiguration.java:788)
	at org.deeplearning4j.nn.transferlearning.TransferLearning$GraphBuilder.addLayer(TransferLearning.java:817)
	at com.sax2.muaaz.joosuf.yolo_neural_network.YoloAlgorithm.main(YoloAlgorithm.java:152)

any ideas cause im completely stuck now

**Comment by tahaemara** [comment]
Which version of deeplearning4j do you have?

**Comment by thekevshow** [comment]
I am having the same issue with updated version to beta4 if there is any insight on this.

**Comment by mbt925** [comment]
I am having it too with version beta3.

**Comment by antecessor** [comment]
Beta 5 has also same issue.
